/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false cloudflare-env.d.ts` (hash: 26c05f8dd818e6d01da85220a85627ac)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	BETA_MODE: "true";
	AUTH_SECRET: string;
	AUTH_GOOGLE_ID: string;
	AUTH_GOOGLE_SECRET: string;
	OWNER_EMAILS: string;
	UPSTASH_REDIS_REST_URL: string;
	UPSTASH_REDIS_REST_TOKEN: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
