import fs from 'node:fs';import path from 'node:path';
import { DEPARTMENT_TAXONOMY, OVERSIGHT_TAXONOMY, LEGACY_DEPARTMENT_ALIASES, LEGACY_BRANCH_ALIASES, REFERENCE_AGENT_ASSIGNMENTS, skillPolicy, blueprintPolicy } from '../src/lib/departmentTaxonomy';
import { getDepartment, hashInstructions, HQ, QA } from '../src/lib/departments';
const root=path.resolve('..');const out=path.resolve(process.argv[2] ?? path.join(root,'verification','semantic-taxonomy')); fs.mkdirSync(out,{recursive:true});
const raw=JSON.parse(fs.readFileSync('data/jobs.json','utf8'));const jobs: {id:string;steps:{id:string;kind:string;departmentId?:string;instructionsHash?:string}[]}[] = Array.isArray(raw)?raw:Array.isArray(raw.jobs)?raw.jobs:Object.values(raw.jobs??raw);
const saved=jobs.flatMap((job:{id:string;steps:{id:string;kind:string;departmentId?:string;instructionsHash?:string}[]})=>job.steps.filter(s=>s.instructionsHash).map(s=>{const dept=s.departmentId?getDepartment(s.departmentId):s.kind==='qa'?QA:['plan','reconcile','final'].includes(s.kind)?HQ:undefined;const current=dept?hashInstructions(dept.file):null;return {jobId:job.id,stepId:s.id,departmentId:s.departmentId??dept?.id??null,recordedHash:s.instructionsHash,currentHash:current,changed:current!==null&&current!==s.instructionsHash};}));
const manifest=JSON.parse(fs.readFileSync(path.join(root,'skills-lock.json'),'utf8'));
const skills=Object.keys(manifest.skills).map(id=>({id,...skillPolicy(id)}));
const blueprintRecords=JSON.parse(fs.readFileSync('src/data/vaultCapabilities.json','utf8'));
fs.writeFileSync(out+'/semantic-canonical-registry.json',JSON.stringify({departments:DEPARTMENT_TAXONOMY,oversight:OVERSIGHT_TAXONOMY,aliases:LEGACY_DEPARTMENT_ALIASES,branchAliases:LEGACY_BRANCH_ALIASES,referenceAgents:REFERENCE_AGENT_ASSIGNMENTS,runtimeCompatibility:{'sales-bd':'Strategy_Intelligence_Agent_System.md','sales_bd':'Sales_BD_Agent_System.md','meta-ads':'Growth_Demand_Agent_System.md'},permissionAliasesExpand:false, identitySchemaVersion:2},null,2));
fs.writeFileSync(out+'/semantic-history-hashes.json',JSON.stringify({rerunPolicy:'explicit-original-or-current-for-new-reruns; revisions-current',legacyOriginalSnapshotsAvailable:false,jobCount:jobs.length,hashedSteps:saved.length,changedHashes:saved.filter(s=>s.changed).length,steps:saved},null,2));
fs.writeFileSync(out+'/semantic-skill-manifest-policy.json',JSON.stringify({note:'Upstream manifest references preserved; no claim of installed or operational skills. Unmapped references carry no department execution scope. Repository Impeccable scope is separately classified as design/engineering.',entries:skills},null,2));
fs.writeFileSync(out+'/semantic-blueprint-policy.json',JSON.stringify(blueprintRecords.map((r:{id:string;category:string})=>({id:r.id,categoryId:r.category,...blueprintPolicy(r.category)})),null,2));
console.log(JSON.stringify({jobs:jobs.length,hashedSteps:saved.length,hashesDiffer:saved.filter(s=>s.changed).length,manifestReferences:skills.length,unmappedReferences:skills.filter(s=>s.mappingState==='unmapped').length,blueprints:blueprintRecords.length,unmappedBlueprints:blueprintRecords.filter((r:{category:string})=>blueprintPolicy(r.category).mappingState==='unmapped').length}));

