import assert from 'node:assert/strict';
import {presentEntity,entityType,entityBrandAsset,safeEntitySource} from '../src/lib/spatial/entityPresentation';
import type {GraphNode} from '../src/lib/spatial/obsidianReader';
const base:GraphNode={id:'department:marketing',title:'Brand & Growth Marketing',source:'agents',categoryLabel:'Department Systems',color:'#fff',path:'Marketing.md',excerpt:'Recorded mandate',degree:0,taxonomyKind:'department',content:'# Record\n## Overview\nBrand & Growth Marketing owns market positioning and demand strategy.\n\n## Responsibilities\n- Create campaigns'};
const department=presentEntity(base,[base],[]);
assert.equal(department.type,'Department');assert.equal(department.current.length,0);assert.match(department.summary,/Responsible for market positioning/);assert.doesNotMatch(department.summary,/Responsibilities/);
const specialist={...base,id:'specialist:frontend',source:'specialists',taxonomyKind:'specialist' as const,title:'Frontend Developer',excerpt:'Builds accessible interfaces.',content:'---\nemoji: 🖥️\n---\n# Personality\nYou are a personality'};
assert.equal(presentEntity(specialist,[specialist],[]).summary,'Builds accessible interfaces.');
for(const [source,label] of [['mcp','Connector'],['models','AI Model'],['capabilities','Capability'],['docs','Product & Architecture']]) assert.equal(entityType({...base,source,taxonomyKind:undefined}),label);
const connector={...base,id:'mcp:github',title:'GitHub',source:'mcp',taxonomyKind:undefined,content:'**Status:** Configured (connected); availability requires a live check\n**Transport:** HTTP\n**Allowed Departments:** Brand & Growth Marketing'};
const projected=presentEntity(connector,[base,connector],[{source:base.id,target:connector.id,type:'structural',relation:'permission',permissionScopes:['marketing']}]);
assert.equal(projected.current[0].value,'Configured · live connection not checked');assert.equal(projected.related[0].relation,'permission');assert.equal(projected.related[0].node.id,base.id);assert.equal(projected.related[0].scopes[0],'marketing');
assert.equal(entityBrandAsset('GitHub'),'/brands/github.svg');for(const title of ['Apollo.io','Higgsfield AI','Meta Ads','Executive Orchestration']) assert.equal(entityBrandAsset(title),null);
const redacted=safeEntitySource('https://user:secret@example.test/path?token=private\nAPI_KEY=never-show-this\nsk-abcdefghijklmnopqr');assert.doesNotMatch(redacted,/secret|private|never-show-this|abcdefghijklmnopqr/);
assert.ok(base.content?.includes('Responsibilities'));assert.equal(department.source,base.content);
console.log('PASS entity classification, concise recorded mandates, omitted unknown current state, specialist source isolation, real relationship semantics, documented brand-only identity, credential redaction and preserved originals.');
const personalized=presentEntity(connector,[base,connector],[{source:base.id,target:connector.id,type:'structural',relation:'permission'}],{workspaceDisplayName:'Acme',language:'bn',preferredTone:'formal',executionPreference:'free-local-first',recommendationsEnabled:false});
assert.match(personalized.summary,/Acme/);assert.doesNotMatch(personalized.summary,/GrowForge|used by/);
assert.deepEqual(personalized.facts,projected.facts);assert.deepEqual(personalized.current,projected.current);
assert.match(personalized.role!,/permitted/);assert.match(personalized.role!,/do not establish actual usage/);
assert.equal(presentEntity(base,[base],[]).role,null);
const assigned=presentEntity(specialist,[specialist,base],[{source:specialist.id,target:base.id,type:'structural',relation:'assignment'}]);
assert.match(assigned.role!,/not execution authority or an active task/);
const capability={...base,id:'branch:demand',title:'Demand Generation',taxonomyKind:'branch' as const,departmentId:'marketing'};
assert.match(presentEntity(capability,[capability],[]).role!,/not executable permission or implementation readiness/);
assert.doesNotMatch([assigned.role,personalized.role].join(' '),/may execute|may modify|action-enabled|authorized to perform/i);
