import assert from 'node:assert/strict';
import fs from 'node:fs';
import { intelligenceRecords, usageFields, executionFields, evidenceScope } from '../src/components/spatial/dive/intelligenceModel';
import { noraSurfaceContext } from '../src/lib/noraSurfaceContext';
import type { CoreState, CoreJobView } from '../src/lib/coreState';
const core: CoreState = { generatedAt:'2026-10-02T00:00:00Z',job:null,jobs:[{id:'real',title:'Recorded',status:'error',percent:0,createdAt:'2026-10-01T00:00:00Z',isTest:false},{id:'test',title:'Fixture',status:'running',percent:0,createdAt:'',isTest:true}],systems:{probes:[{id:'ollama',label:'Local',online:false,detail:'offline in public preview',latencyMs:null}],mcp:{count:0,servers:[]},models:{count:0,list:[]},routing:'cloud-first',pendingApprovals:0,pendingConsultations:0,vault:{reachable:false,noteCount:0,latestDaily:null}}};
assert.deepEqual(intelligenceRecords(null),[]);
const records=intelligenceRecords(core);assert.equal(records.length,2);assert.ok(records.every(r=>r.jobId==='real'));assert.equal(records[0].fields[0].value,'error');
const usage: import('../src/components/spatial/dive/intelligenceModel').StepUsage[]=[{stepId:'step',stepLabel:'Plan',records:[{provider:'ollama',model:'model',inputTokens:null,outputTokens:12,durationMs:20,timestamp:core.generatedAt}]}];
assert.equal(usageFields(usage).find(f=>f.label==='Reported tokens')?.state,null);
assert.equal(usageFields(usage).find(f=>f.label==='Input tokens')?.value,'Not recorded');
assert.match(usageFields([]).find(f=>f.label==='Reported tokens')!.value,/Unavailable/);
usage[0].records[0].inputTokens=8;
const total=usageFields(usage).find(f=>f.label==='Reported tokens');assert.equal(total?.value,'20');assert.equal(total?.state,'DERIVED');assert.ok(total?.formula);
assert.ok(usageFields(usage).every(f=>!f.label.includes('cost')));
const job={steps:[{id:'step',label:'Plan',status:'done',startedAt:'2026-10-02T00:00:00Z',finishedAt:'2026-10-02T00:00:02Z'}]} as CoreJobView;
assert.equal(executionFields(job).find(f=>f.state==='DERIVED')?.value,'2000 ms');
job.steps[0].finishedAt='2026-10-01T00:00:00Z';assert.ok(!executionFields(job).some(f=>f.state==='DERIVED'));
const scope=evidenceScope(records[0],[]);assert.ok(scope.context.includes('"apiCost":null'));
assert.ok(noraSurfaceContext('Dive In',null,null,null,null,null,null,null,scope).includes('"evidenceId":"execution:real"'));
assert.ok(noraSurfaceContext('CORE',null,null,null,null,null,null,null,scope).includes('"selection":null'));
const source=fs.readFileSync('src/components/spatial/dive/IntelligenceLens.tsx','utf8');
assert.match(source,/body\.jobId !== record\.jobId/);assert.match(source,/body\.job\?\.id !== record\.jobId/);assert.match(source,/controller\.abort/);assert.match(source,/growforge:intelligence-record[\s\S]*detail: null/);
assert.ok(!source.includes('estimateCost'));
assert.match(source,/\[record\.jobId, record\.domain, record\.timestamp\]/, 'Detailed evidence refreshes when its parent snapshot changes');
assert.match(source,/read\.snapshot === record\.timestamp \? read\.fields : \[\]/, 'Old detail fields must not be attributed to a newer snapshot');
console.log('PASS Intelligence: test/preview isolation, original IDs, missing tokens/cost, formulas, backwards timestamps, NORA scope/cleanup, detail identity validation.');
