import assert from 'node:assert/strict';
import fs from 'node:fs';
import { workflowRecords, filteredWorkflows, workflowScope, PIPELINE_ID } from '../src/components/spatial/dive/workflowModel';
import { noraSurfaceContext } from '../src/lib/noraSurfaceContext';
import type { SpatialGraphData } from '../src/lib/spatial/obsidianReader';

const graph:SpatialGraphData={nodes:[{id:'agent:web',title:'Web & Platform Engineering',source:'agents',departmentId:'web_platform_engineering',categoryLabel:'Department Systems',color:'#fff',path:'Web_Development_Agent_System.md',excerpt:'',degree:0}],links:[],categories:[],summary:{totalNotes:1,totalConnections:0,totalSources:1}};
assert.deepEqual(workflowRecords(null),[]);
assert.deepEqual(workflowRecords({...graph,nodes:[]}),[]);
const records=workflowRecords(graph);
assert.equal(records.length,1);
const record=records[0];assert.equal(record.id,PIPELINE_ID);assert.equal(record.type,'internal-pipeline');
assert.equal(record.steps.length,7);assert.equal(new Set(record.steps.map(step=>step.id)).size,7);
for(const step of record.steps)assert.ok(step.dependsOn.every(id=>record.steps.find(candidate=>candidate.id===id)));
assert.equal(record.steps.filter(step=>step.dynamic).length,1);
assert.equal(record.relationships.filter(link=>link.type==='conditional-department-use').length,8);
assert.ok(record.relationships.every(link=>link.id && link.sourceId && link.targetId && link.evidence==='structure'));
assert.equal(filteredWorkflows(records,'web_platform_engineering').length,1);
assert.equal(filteredWorkflows(records,'unknown').length,0);
assert.equal(filteredWorkflows(records,null).length,1);
assert.ok(!record.categories.Agents && !record.categories.Cost && !record.categories.Cadence && !record.categories.Tools);
const scope=workflowScope(record,record.steps[3]);
assert.match(scope.context,/Parallel|plan|assigned/);
assert.match(noraSurfaceContext('Dive In',null,null,null,null,scope),/"workflowId":"procedure:orchestrator:resumePipeline"/);
assert.match(noraSurfaceContext('Dive In',null,null,null,null,scope),/selectedStep/);
for(const surface of ['CORE','Explore','Systems'] as const)assert.match(noraSurfaceContext(surface,null,null,null,null,scope),/"selection":null/);
assert.match(noraSurfaceContext('Dive In',null,null,null,null,null),/"selection":null/);
assert.ok(noraSurfaceContext('Dive In',null,null,null,null,{...scope,context:'x'.repeat(10000)}).length<2500);
// Detect source-contract drift without importing or running the execution engine.
const source=fs.readFileSync('src/lib/orchestrator.ts','utf8');
for(const id of ['brief','plan','research','reconcile','qa','final'])assert.ok(source.includes(`id: "${id}"`));
for(const name of ['createAndStartJob','resumePipeline','runPlanStage','runResearchStage','runDepartmentsStage','runReconcileStage','runQaStage','runFinalStage'])assert.ok(source.includes(name));
assert.match(source,/dependsOn: deptSteps\.map/);
assert.match(source,/if \(pendingAssignments.length > 0\) await runDepartmentsStage/);
assert.match(source,/await waitForApproval/);
const approval=fs.readFileSync('src/app/api/jobs/[id]/approve/route.ts','utf8');assert.match(approval,/if \(!job.finalOutput\)/);assert.match(approval,/approvedAt: new Date/);
const ui=fs.readFileSync('src/components/spatial/dive/WorkflowsLens.tsx','utf8');
assert.match(ui,/detail:null/);assert.match(ui,/return\(\)=>/);assert.ok(!ui.includes('demo=true'));
console.log('PASS pipeline source contract, stable definition/step/relationship IDs, dynamic dependency group, no inferred skill/automation/runtime activity, isolated read empty state, department filter and bounded NORA scope.');
