import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import type {CoreState} from '../src/lib/coreState';
import {IDLE_NORA_SIGNAL as idle} from '../src/lib/noraVisualSignal';
import {innerCorePhase,overviewCommandSummary,newlyCompleted} from '../src/components/spatial/dive/overviewCommandModel';
const empty:CoreState={generatedAt:'2026-10-04T00:00:00Z',jobs:[],job:null,systems:{probes:[],mcp:{count:0,servers:[]},models:{count:0,list:[]},routing:'local-first',pendingApprovals:0,pendingConsultations:0,vault:{reachable:false,noteCount:0,latestDaily:null}}};
const running:CoreState={...empty,jobs:[{id:'real-job',title:'Fixture',status:'running',percent:10,createdAt:empty.generatedAt,isTest:false}]};
assert.equal(innerCorePhase(empty,idle),'idle');
assert.equal(innerCorePhase(empty,{...idle,focused:true}),'attentive');
assert.equal(innerCorePhase(empty,{...idle,listening:true}),'listening');
assert.equal(innerCorePhase(empty,{...idle,processing:true}),'thinking');
assert.equal(innerCorePhase(empty,{...idle,streaming:true}),'responding');
assert.equal(innerCorePhase(empty,{...idle,speaking:true}),'speaking');
assert.equal(innerCorePhase(running,idle),'executing');
assert.equal(innerCorePhase({...running,systems:{...running.systems,pendingApprovals:1}},idle),'awaiting');
assert.equal(innerCorePhase(empty,idle,false,true),'success');
assert.equal(innerCorePhase(empty,{...idle,error:true}),'degraded');
assert.equal(innerCorePhase({...running,jobs:running.jobs.map(job=>({...job,isTest:true}))},idle),'idle');
const completed={...running,jobs:running.jobs.map(job=>({...job,status:'done' as const}))};
assert.equal(newlyCompleted(null,completed),false,'historical completion is not a new success');
assert.equal(newlyCompleted(running,completed),true);
assert.equal(overviewCommandSummary(completed)?.running,0);
assert.equal(overviewCommandSummary(completed)?.completed,1);
assert.equal(overviewCommandSummary(null),null);
const composer=readFileSync('src/components/spatial/CoreCommandCenter.tsx','utf8');
assert.match(composer,/streaming:false,speaking:agentSpeaking/,'JSON remains non-streamed; speech follows actual agent PCM receipts');
assert.match(composer,/setListening\(receiving\)/,'primary listening follows backend audio receipts');
const voiceClient=readFileSync('src/lib/livekitVoiceClient.ts','utf8');
assert.match(voiceClient,/data.audioFrameCount > 0/,'published microphone alone cannot establish listening');
assert.match(voiceClient,/data.inputParticipant !== this.room\?\.localParticipant.identity/,'receipts belong to this participant');
const overview=readFileSync('src/components/spatial/dive/OverviewRuntime.tsx','utf8');
assert.match(overview,/if\(!signal\.responseId \|\| signal\.processing \|\| signal\.error\)\{clearTimeout\(timer\);setResponseVisible\(false\);\}/,'cleared/new/error response lifecycle invalidates old subtitle and response phase');
assert.match(overview,/useEffect\(\(\)=>\(\)=>clearTimeout\(completionTimer\.current\),\[\]\)/,'success reset timer belongs to component lifetime, not polling snapshots');
assert.match(overview,/completionTimer\.current=setTimeout\(\(\)=>setCompletedNow\(false\),1400\)/,'observed success has a bounded reset');
console.log('PASS real lifecycle priority, future speech/stream hooks, test exclusion, historical success suppression and truthful summary; fixtures only, no provider/store calls.');

assert.doesNotMatch(overview, /OverviewInstrument/, 'Overview surfaces remain text-led');
// Overview V2-B: per-service latency lives in the Tools lens; Overview shows reachability only through the Snapshot.
assert.doesNotMatch(overview, /CapabilitySignal/, 'no per-service latency card on Overview');
assert.match(overview, /operationalStrip\(snapshot\)/, 'service reachability reaches Overview through the measured Snapshot');
