import assert from 'node:assert/strict';
import { departmentRecords } from '../src/components/spatial/dive/departmentModel';
import { DIVE_LENSES } from '../src/components/spatial/dive/overviewModel';
import { noraSurfaceContext } from '../src/lib/noraSurfaceContext';
import type { SpatialGraphData } from '../src/lib/spatial/obsidianReader';
// Canonical nine-lens order (Finance added 2026-10-05). Parity with the registry is pinned in test-dive-foundation.
assert.deepEqual(DIVE_LENSES.slice(0,4),['Overview','Missions','Context','Finance']);
assert.deepEqual(DIVE_LENSES,['Overview','Missions','Context','Finance','Departments','Agents','Workflows','Tools','Intelligence']);
const empty=departmentRecords(null);
assert.equal(empty.filter(r=>r.taxon.kind==='department').length,8);assert.equal(empty.filter(r=>r.taxon.kind==='oversight').length,2);
assert.equal(new Set(empty.map(r=>r.taxon.id)).size,10);assert.ok(empty.every(r=>Object.keys(r.categories).length===0));
const taxon=empty[0].taxon;
const graph:SpatialGraphData={nodes:[{id:'real-source',departmentId:taxon.id,taxonomyKind:'department',title:taxon.name,source:'agents',categoryLabel:'Department',color:'#fff',path:taxon.file,excerpt:'Recorded strategy purpose.',degree:1},{id:'tool',title:'Notion',source:'mcp',categoryLabel:'Connector',color:'#fff',path:'npx',excerpt:'',degree:1}],links:[{source:'real-source',target:'tool',type:'structural',relation:'permission'}],categories:[],summary:{totalNotes:2,totalConnections:1,totalSources:2}};
const record=departmentRecords(graph)[0];assert.match(record.categories.Tools[0],/permitted relationship/);assert.equal(record.categories.Purpose[0],'Recorded strategy purpose.');
for(const category of ['Skills','Workflows','Missions','Approvals'])assert.ok(!record.categories[category]);
const context={departmentId:taxon.id,title:taxon.name,kind:'department' as const,context:'x'.repeat(9000)};
assert.match(noraSurfaceContext('Dive In',null,null,context),/"layer":"Departments"/);assert.ok(noraSurfaceContext('Dive In',null,null,context).length<2600);
for(const surface of ['CORE','Explore','Systems'] as const)assert.match(noraSurfaceContext(surface,null,null,context),/"selection":null/);
assert.match(noraSurfaceContext('Dive In',null,null,null),/"selection":null/);
console.log('PASS canonical eight + separate oversight, stable IDs, missing-source omissions, permitted relationship truthfulness, lens ordering, bounded department context and cross-surface dismissal isolation.');
